// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmw4Ov_ZIkeA2upCRpfAQalrXi6lHeKuc',
    appId: '1:445057758214:android:4763573d15fe09dbbd7f87',
    messagingSenderId: '445057758214',
    projectId: 'planner-7fc4d',
    storageBucket: 'planner-7fc4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbwcyjpUjUQZ6gfLwKXGam871nw4rt6eM',
    appId: '1:445057758214:ios:931d8e0b3725cf8ebd7f87',
    messagingSenderId: '445057758214',
    projectId: 'planner-7fc4d',
    storageBucket: 'planner-7fc4d.appspot.com',
    iosBundleId: 'com.bellico.planner',
  );
}
